version: "3.8"

networks:
    imagine-network:
        driver: bridge

volumes:
    imagine-db:
    pgadmin-data:
    seq-data:

services:
    imagine_todo_api:
        image: ${DOCKER_REGISTRY-}imaginetodoapi
        build:
            context: Imagine_todo_api
            dockerfile: Imagine_todo_api/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - imagine-network
            
    imagine-database:
        container_name: imagine.database
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        networks:
            - imagine-network
        volumes:
            - imagine-db:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - imagine-network
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@imagine.net
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
            
    imagine.seq:
        container_name: imagine.seq
        image: datalust/seq:latest
        networks:
          - imagine-network
        environment:
          - ACCEPT_EULA=Y
        ports:
          - "5341:5341"
          - "8081:80"
        volumes:
          - seq-data:/data

           
  