version: "3.8"

networks:
    taskify-network:
        driver: bridge

volumes:
    taskify-db:
    pgadmin-data:
    seq-data:

services:
    imagine_todo_api:
        image: ${DOCKER_REGISTRY-}taskify_api
        build:
            context: taskify_api
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        networks:
            - taskify-network
            
    imagine-database:
        container_name: imagine.database
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        networks:
            - taskify-network
        volumes:
            - taskify-db:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - taskify-network
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@imagine.net
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:5050"
            
    imagine.seq:
        container_name: imagine.seq
        image: datalust/seq:latest
        networks:
          - taskify-network
        environment:
          - ACCEPT_EULA=Y
        ports:
          - "5341:5341"
          - "8081:8081"
        volumes:
          - seq-data:/data
          
    imagine_todo_ui:
        image: ${DOCKER_REGISTRY-}imaginetodoui
        build:
            context: Taskify_ui
            dockerfile: Dockerfile
        ports:
            - "4200:80"
        networks:
            - taskify-network      

           
  